# https://cdnjs.com/libraries/font-awesome
FONTAWESOME_URL=https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.1
download-fontawesome-css:
	#curl  $(FONTAWESOME_URL)/css/brands.min.css -o fontawesome/brands.min.css
	#curl  $(FONTAWESOME_URL)/css/fontawesome.min.css -o fontawesome/fontawesome.min.css
	#curl  $(FONTAWESOME_URL)/css/regular.min.css -o fontawesome/regular.min.css
	#curl  $(FONTAWESOME_URL)/css/solid.min.css -o fontawesome/solid.min.css
	curl  $(FONTAWESOME_URL)/webfonts/fa-brands-400.woff2 -o webfonts/fa-brands-400.woff2
	curl  $(FONTAWESOME_URL)/webfonts/fa-regular-400.woff2 -o webfonts/fa-regular-400.woff2
	curl  $(FONTAWESOME_URL)/webfonts/fa-solid-900.woff2 -o webfonts/fa-solid-900.woff2
