

vue-production:
	ln -s vue.esm-browser.prod.min.js vue.js

vue-development:
	ln -s vue.esm-browser.min.js vue.js

vue3-sfc-loader-map:
	# wget https://cdn.jsdelivr.net/npm/vue3-sfc-loader@0.9.5/dist/vue3-sfc-loader.esm.js
	# wget https://cdn.jsdelivr.net/npm/vue3-sfc-loader@0.9.5/dist/vue3-sfc-loader.js
	wget https://app.unpkg.com/vue3-sfc-loader@0.9.5/files/dist/vue3-sfc-loader.esm.js.map
	#wget https://cdn.jsdelivr.net/npm/vue3-sfc-loader@0.9.5/dist/vue3-sfc-loader.js.map
	#wget https://cdn.jsdelivr.net/npm/vue3-sfc-loader@0.9.5/dist/vue3-sfc-loader.esm.js.map



# https://github.com/katspaugh/wavesurfer.js
# https://www.jsdelivr.com/package/npm/wavesurfer.js
wavesurfer:
	wget https://cdn.jsdelivr.net/npm/wavesurfer.js@7.12.1/dist/wavesurfer.esm.js

# note: c0ckp1t originally uses  "1.11.2";
# latest is exports.version = "1.43.6";  as of 2026 January
ace-editor:
	ln -s /src-noconflict ./ace-editor